[package]
name = "dymo_hid"
version = "0.1.0"
authors = ["puzzlewolf <mail@nora.pink>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.17.4"
image = "0.23.3"
structopt = "0.3"
